version: '3.8'

services:
  app1:
    build: .
    ports:
      - "5001:8080"
    environment:
      - name=app1
  
  app2:
    build: .
    ports:
      - "5002:8080"
    environment:
      - name=app2
  
  app3:
    build: .
    ports:
      - "5003:8080"
    environment:
      - name=app3